language: ruby
cache: bundler

bundler_args: --without development

rvm:
  - jruby-9.2.5.0 # latest stable
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - truffleruby
  - ruby-head

env:
  global:
    - JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"
  matrix:
    - NIO4R_PURE=false
    - NIO4R_PURE=true

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
  fast_finish: true

notifications:
  irc: "irc.freenode.org#celluloid"
